### PR TITLE
Fix problems with result save functions, and improve unit test coverage.

### PR DESCRIPTION
**Pull request by celiot-IDM**
A couple of under-used CSV creation functions broke when the results structure changed, but the breaks weren't picked up by unit testing or use. Now fixed.

### CODE REVIEW

**Comment by celiot-IDM** [comment]
@MeWu-IDM : image problems?

image

**Comment by MeWu-IDM** [comment]
> @MeWu-IDM : image problems?
this should fix it https://github.com/InstituteforDiseaseModeling/PACE-HRH/pull/211  possibly some compiling error occurred for dependant package, use binary instead

**Comment by celiot-IDM** [comment]
@MeWu-IDM : your devtools fix worked.

**Comment by celiot-IDM** [comment]
> 

No, I didn't create an issue, but I can describe here:

- SaveSuiteResults() would fail if the results structure didn't have a $SeasonalityResults section. The correct behavior is to emit a CSV file of annual results.
- SaveResults() would also fail outright.

Root cause in both cases is rearrangement of the results structure to move annual results to a sub-section. Reason not found before: (1) nobody is using annual results anymore, and (2) insufficient unit test coverage.

**Comment by MeWu-IDM** [comment]
ok for the current researcher scenario the SaveSuiteResults still returns the same data so I think this is ok, however, it seems runSeasonalityExperiment  will always return SeasonalityResults even if there is no seasonality (it'll just be results distributed evenly over 12 months) so I am not sure why we need to have this condition for saveSuiteResults.

**Review by MeWu-IDM — APPROVED** [review]

**Comment by celiot-IDM** [comment]
> 

@MeWu-IDM : You're not wrong ... at this time we always apply seasonality, so in theory there's no need to ever save the annual results except (and this is the point) as intermediate reference data for debugging purposes. I debated removing the annual versions entirely, but it was easy to keep them working for a while longer, so I took the path of least resistance ;-)

**Pull request merged**
